source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'IntervalSlider_Example', :exclusive => true do
  pod "IntervalSlider", :path => "../"
end

target 'IntervalSlider_Tests', :exclusive => true do
  pod "IntervalSlider", :path => "../"

  pod 'FBSnapshotTestCase'
end
